version: '3.3'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
      build: .
      command: sh -c "/start.sh"
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        - db

volumes:
  postgres_data:
